import { useQuery } from "@tanstack/react-query";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import useWalletApi from "~/services/useWalletApi";

interface StepProps {
  title: string;
  subtitle: string;
  link: string;
}
const Step = ({ link, subtitle, title }: StepProps) => (
  <Link
    className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
    href={link}
  >
    <h3 className="text-2xl font-bold">{title}</h3>
    <div className="text-lg">{subtitle}</div>
  </Link>
);

const Terminal = () => {
  <div className="relative z-10 col-span-3 -ml-10 rounded-xl bg-slate-800 shadow-lg dark:shadow-none dark:ring-1 dark:ring-inset dark:ring-white/10 xl:ml-0"></div>;
};

interface FetchAccountProps {
  inLedgerLive: boolean;
}
const FetchAccount = ({ inLedgerLive }: FetchAccountProps) => {
  const { walletApiSdk } = useWalletApi();

  const [currencyIds, setCurrencyId] = useState(["bitcoin"]);
  const availableCurrencys = [
    ["bitcoin"],
    ["ethereum"],
    ["bitcoin", "ethereum"],
  ];

  const { data, refetch } = useQuery({
    queryKey: ["account", ...currencyIds],
    queryFn: async () => {
      const info = await walletApiSdk?.wallet.info();

      // console.log("currencyIds", currencyIds, walletApiSdk);
      const accountList = await walletApiSdk?.account?.list({
        currencyIds,
      });

      if (!accountList) throw new Error("Error Happen");

      console.log("info", info);
      // you can fetch other stuff here like nft or Idk what you want

      console.log("accountList", accountList);
      return accountList;
    },
    enabled: !!walletApiSdk,
  });

  return (
    <div className="rounded-lg bg-white/5 p-3">
      <div className="text-2xl">Fetch accounts</div>
      <div> Allow you to fetch an array of account by currency Id</div>
      <div className="my-2 w-fit rounded-lg bg-white/5 px-2 py-1">
        manifest permission : account.list
      </div>
      <div className="mb-4 text-sm text-neutral-70">
        {" "}
        note that you have to declare all currency you want to call in the
        currencies section of the manifest
      </div>
      <code className=" rounded-lg bg-white/10 px-2 py-1">
        {`
        const accountList = await walletApiSdk?.account?.list({
          currencyIds,
        })`}
      </code>
      <div className="mt-3">accountList is of type Account[]</div>
      {inLedgerLive && (
        <div className="mt-6 flex gap-2">
          {availableCurrencys.map((availableCurrency) => (
            <div
              key={availableCurrency.toString()}
              className="cursor-pointer rounded-lg bg-white/10 px-3 py-2"
              onClick={() => {
                setCurrencyId(availableCurrency);
                refetch({ queryKey: ["account", ...currencyIds] }).catch(
                  console.log
                );
              }}
            >
              <div className="flex gap-2">
                {availableCurrency.map((c) => (
                  <div key={c}>{c}</div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
      <div className="mt-3 flex flex-col">
        {data?.map((account) => (
          <div key={account.address}>
            <div>{account.name}</div>
            <div className="text-neutral-70">{account.address}</div>
          </div>
        ))}
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const { walletApiSdk } = useWalletApi();

  const { data: infoWalletApi } = useQuery({
    queryKey: ["info"],
    queryFn: () => walletApiSdk?.wallet.info(),
    enabled: !!walletApiSdk,
  });

  return (
    <>
      <Head>
        <title>Ledger Unoficial doc</title>
        <meta name="description" content="Generated by pierre-alexis" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black text-white">
        <div className="container mx-auto flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-center text-3xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Wallet Api{" "}
            <span className="text-[hsl(280,100%,70%)]">Unofficial</span> Doc
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Step
              link="/load-manifest"
              title="First Step →"
              subtitle="Load a manifest to see the app"
            />
            <Step
              link="install-walletapi"
              title="Install Wallet Api"
              subtitle="Install wallet Api"
            />
          </div>
        </div>
        <div className="container mx-auto mb-7 text-center">
          Clone me if you want to have the code
          <div>
            <Link
              className="text-orange-400"
              href="https://github.com/pdeville-ledger/walletapi-unofficial-docs"
              target="_blank"
            >
              https://github.com/pdeville-ledger/walletapi-unofficial-docs
            </Link>
          </div>
        </div>
        <div className="container mx-auto flex flex-col gap-4 pb-12">
          {!infoWalletApi ? (
            <div className="flex items-center justify-center gap-2">
              It look like you are not in ledger live
              <div className="h-4 w-4 rounded-full bg-error-60"></div>
            </div>
          ) : (
            <>
              <div className="flex items-center justify-center gap-2">
                Connected to ledger Live
                <div className="h-4 w-4 rounded-full bg-sucess-60"></div>
              </div>
              <div className="flex items-center justify-center gap-2">
                <div>{infoWalletApi.wallet.name}</div>
                <div>{infoWalletApi.wallet.version}</div>
              </div>
            </>
          )}
          <FetchAccount inLedgerLive={!!infoWalletApi} />
        </div>
      </main>
    </>
  );
};

export default Home;
